### ISSUE TITLE
private fields are not getting set

### ISSUE THREAD

**Issue by sonalgupta** [percyliang/fig#20]
if an option is declared public, it is set as expected by Execution.run(args, object). However, if an option is private, it does not get set by calling the run function. 

For example, in the Sample.java file, I changed the line to 

private int N = 3; 

and the output of 

java -cp .:../fig.jar Sample -N 10 -random 42 -list dog cat -set apple pear 

was

main() {
  Simulating {
    Sample 0: -0.324901
    Sample 1: -0.259597
    Sample 2: 0.741113
  }
  Statistics {
    Mean: 0.052205
    Stddev: 0.487861
  }
}

Am I missing some setting or a function that needs to be called for private options?

**Comment by percyliang** [comment]
You cannot set private options, unfortunately (because they're private and
that would be dangerous).

**Comment by sonalgupta** [comment]
Thanks Percy for the reply --  just saw this after doing a PR. I am not deleting it just in case you wanna take a look.

**Comment by percyliang** [comment]
Oh, I guess that works - I merged it in - thanks for the contribution!
